# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02771f20840dacb48dcf4905a01e5e1233b336e201f63db3a8553e12f25c61d5455c54b0a746551da82e3e5d2506bbb8ca2e483565aad4c6f4745348f763dd2d

test:
  secret_key_base: 3f68e31a0b12903dd7591521bbb887d41f15a961efb9ca382ba8b98832a04d61e0e88b67dd8c539102ae1a91b55499c80ed5feef6305525bc47d509f2315e6cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
